"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Tags, Plus, Trash2, Loader2, Pencil, Check, X, Eye } from "lucide-react";
import { toast } from "sonner";
import AppShell from "@/components/layout/AppShell";
import { Card, Input, Badge } from "@/components/ui";
import Button from "@/components/ui/Button";
import Pagination from "@/components/ui/Pagination";
const PAGE_SIZE = 10;
export default function CategoriesPage() {
  const [categories, setCategories] = useState([]); const [name, setName] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const [editingId, setEditingId] = useState(null); const [editName, setEditName] = useState(""); const [page, setPage] = useState(1);
  async function load(){ const res=await fetch("/api/categories",{cache:"no-store"}); const data=await res.json(); setCategories(data.categories||[]); }
  useEffect(()=>{load();},[]);
  async function handleSubmit(e){e.preventDefault(); if(!name.trim())return; setSaving(true); setError(""); const res=await fetch("/api/categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})}); const data=await res.json(); setSaving(false); if(!res.ok){setError(data.error);toast.error(data.error||"Something went wrong.");return;} toast.success("Category added.");setName("");load();}
  async function saveEdit(id){ if(!editName.trim())return; const res=await fetch(`/api/categories?id=${id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:editName})}); const data=await res.json(); if(!res.ok){toast.error(data.error||"Could not update category.");return;} toast.success("Category updated.");setEditingId(null);load(); }
  async function handleDelete(id){if(!confirm("Delete this category?"))return;const res=await fetch(`/api/categories?id=${id}`,{method:"DELETE"});const data=await res.json();if(res.ok)toast.success("Category deleted.");else toast.error(data.error||"Could not delete category.");load();}
  const pages=Math.max(1,Math.ceil(categories.length/PAGE_SIZE)); const rows=useMemo(()=>categories.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE),[categories,page]);
  return <AppShell title="Categories"><div className="grid grid-cols-1 lg:grid-cols-3 gap-5"><Card className="p-5 h-fit"><div className="flex items-center gap-2 mb-4"><div className="w-8 h-8 rounded-lg bg-gold/10 border border-gold-dim/40 flex items-center justify-center text-gold-soft"><Tags className="w-4 h-4"/></div><h2 className="font-display text-base text-text">New Category</h2></div><form onSubmit={handleSubmit} className="space-y-3"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Sparkling Wine"/>{error&&<p className="text-xs text-danger">{error}</p>}<Button type="submit" className="w-full" disabled={saving}>{saving?<Loader2 className="w-4 h-4 animate-spin"/>:<Plus className="w-4 h-4"/>}Add Category</Button></form></Card>
  <Card className="lg:col-span-2 overflow-hidden"><div className="divide-y divide-border-soft">{rows.length===0&&<p className="px-5 py-10 text-center text-text-faint text-sm">No categories yet.</p>}{rows.map(c=><div key={c.id} className="px-5 py-3.5 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div className="min-w-0 flex-1">{editingId===c.id?<Input autoFocus value={editName} onChange={e=>setEditName(e.target.value)}/>:<p className="text-sm text-text font-medium">{c.name}</p>}<div className="flex gap-2 mt-1"><Badge tone="gold">{c.main_product_count||0} main</Badge><Badge>{c.sub_product_count||c.product_count||0} sub products</Badge></div></div><div className="flex items-center gap-1">{editingId===c.id?<><button onClick={()=>saveEdit(c.id)} className="p-2 text-success hover:bg-success-soft rounded-lg" title="Save"><Check className="w-4 h-4"/></button><button onClick={()=>setEditingId(null)} className="p-2 text-text-muted hover:bg-bg-elevated-2 rounded-lg" title="Cancel"><X className="w-4 h-4"/></button></>:<><Link href={`/categories/${c.id}/products`} className="p-2 text-primary hover:bg-primary/10 rounded-lg" title="View products"><Eye className="w-4 h-4"/></Link><button onClick={()=>{setEditingId(c.id);setEditName(c.name);}} className="p-2 text-text-muted hover:text-primary hover:bg-primary/10 rounded-lg" title="Edit category"><Pencil className="w-4 h-4"/></button><button onClick={()=>handleDelete(c.id)} className="p-2 text-text-muted hover:text-danger hover:bg-danger-soft rounded-lg" title="Delete category"><Trash2 className="w-4 h-4"/></button></>}</div></div>)}</div><Pagination page={page} pages={pages} total={categories.length} label="categories" onPageChange={setPage}/></Card></div></AppShell>;
}
