"use client";
import { useEffect, useState, useCallback } from "react";
import Link from "next/link";
import { Search, Plus, FileText, Eye, Printer } from "lucide-react";
import AppShell from "@/components/layout/AppShell";
import { Card, Badge, Input, Select, TableSkeleton } from "@/components/ui";
import Button from "@/components/ui/Button";
import Pagination from "@/components/ui/Pagination";
import { formatMoney, formatDate } from "@/lib/utils";

export default function InvoicesPage() {
  const [invoices,setInvoices]=useState([]); const [q,setQ]=useState(""); const [status,setStatus]=useState(""); const [loading,setLoading]=useState(true);
  const [page,setPage]=useState(1); const [pages,setPages]=useState(1); const [total,setTotal]=useState(0);
  const load=useCallback(async(targetPage=1)=>{setLoading(true);const params=new URLSearchParams({page:String(targetPage),limit:"10"});if(q)params.set("q",q);if(status)params.set("status",status);const res=await fetch(`/api/invoices?${params}`,{cache:"no-store"});const data=await res.json();setInvoices(data.invoices||[]);setPage(data.page||targetPage);setPages(data.pages||1);setTotal(data.total||0);setLoading(false);},[q,status]);
  useEffect(()=>{const t=setTimeout(()=>load(1),250);return()=>clearTimeout(t);},[load]);
  return <AppShell title="Invoices"><div className="flex flex-col sm:flex-row gap-3 mb-5"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-text-faint"/><Input placeholder="Search invoice no. or customer…" className="pl-9" value={q} onChange={e=>setQ(e.target.value)}/></div><Select value={status} onChange={e=>setStatus(e.target.value)} className="sm:w-48"><option value="">All statuses</option><option value="paid">Paid</option><option value="partial">Partial</option><option value="unpaid">Unpaid</option></Select><Button as={Link} href="/invoices/new"><Plus className="w-4 h-4"/> New Invoice</Button></div>
  {loading&&invoices.length===0?<TableSkeleton rows={6}/>:<Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b border-border-soft text-left text-xs text-text-muted uppercase tracking-wide"><th className="px-5 py-3">Invoice</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Date</th><th className="px-5 py-3 text-center">Items</th><th className="px-5 py-3 text-right">Total</th><th className="px-5 py-3 text-right">Balance</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody>{!loading&&invoices.length===0?<tr><td colSpan="8" className="px-5 py-16 text-center text-text-faint"><FileText className="w-8 h-8 mx-auto mb-2 opacity-50"/>No invoices found.</td></tr>:invoices.map(inv=><tr key={inv.id} className="border-b border-border-soft last:border-0 hover:bg-bg-elevated-2/50"><td className="px-5 py-3.5 font-mono-num">{inv.invoice_no}</td><td className="px-5 py-3.5 text-text-muted">{inv.customer_name||"Walk-in"}</td><td className="px-5 py-3.5 text-text-muted">{formatDate(inv.invoice_date)}</td><td className="px-5 py-3.5 text-center"><Badge>{inv.item_count||0}</Badge></td><td className="px-5 py-3.5 text-right font-mono-num">{formatMoney(inv.total)}</td><td className="px-5 py-3.5 text-right font-mono-num text-text-muted">{formatMoney(inv.balance)}</td><td className="px-5 py-3.5"><Badge tone={inv.status==="paid"?"success":inv.status==="partial"?"info":"danger"}>{inv.status}</Badge></td><td className="px-5 py-3.5"><div className="flex justify-end gap-1"><Link title="View invoice" href={`/invoices/${inv.id}`} className="p-2 rounded-lg text-primary hover:bg-primary/10"><Eye className="w-4 h-4"/></Link><Link title="Open printable invoice" href={`/invoices/${inv.id}`} className="p-2 rounded-lg text-text-muted hover:text-gold-soft hover:bg-gold/10"><Printer className="w-4 h-4"/></Link></div></td></tr>)}</tbody></table></div><Pagination page={page} pages={pages} total={total} label="invoices" onPageChange={load}/></Card>}</AppShell>;
}
